bundler_args: --without development staging production
language: ruby
sudo: true

addons:
  code_climate:
    repo_token: 5e93d3e4af2fece06eccdaa94075cede7ff1c5d11a08757397db989b0056b850
  apt:
    packages:
      - oracle-java8-set-default

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.2.1.deb && env && sudo service elasticsearch start

after_success:
  - bundle exec codeclimate-test-reporter
