webservices:
  build: .
  volumes:
  - .:/app
  links:
  - elasticsearch
  - redis
  environment:
      REDIS_URL: redis://redis:6379/0
      ES_URL: http://elasticsearch:9200
  ports:
  - "3000:3000"
elasticsearch:
  image: elasticsearch
  ports:
  - 9200:9200
redis:
    image: redis:2.6
    ports:
    - 6379:6379
